version: "3.1"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile 
    container_name: app
    environment:
      NODE_ENV: "dev"
      APP_ENV: "test"
      APP_PORT: 3001
      DB_PORT: 5432
      DB_USERNAME: "user"
      DB_PASSWORD: "supersecretpassword"
      DB_DATABASE: "app"
      DB_HOST: db
      NEST_DEBUG: true
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - .env.docker:/app/.env
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "supersecretpassword"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
