version: 2.1
orbs:
  circleci-global-orb: getquin/circleci-global-orb@volatile
workflows:
  main-workflow:
    jobs:
      - circleci-global-orb/test-js:
          context: getquin
          executor: circleci-global-orb/node18
      - circleci-global-orb/build-and-push:
          context: getquin
          requires:
            - circleci-global-orb/test-js
          filters:
            branches:
              only:
                - master
                - production
